/'
Diagrama UML do Sistema de Gerenciamento de Academias (SGA)
Manual: https://plantuml.com/class-diagram#a05971470d7fd711
'/
@startuml sga
skinparam classAttributeIconSize 0


package br.com.sga.datehelper <<Folder>> {

     class DateHelper {
          
     }
}

package br.com.sga.empresa <<Folder>> {
     class Empresa {
          
     }

     class Usuario {

     }
}

package br.com.sga.financeiro <<Folder>> {

     class Caixa {
          
     }

     class Pagamento {

     }
}

package br.com.sga.identidade <<Folder>> {

     class Endereco {

     }

     enum Estado {

     }

     class ValidacaoDadosPessoais {

     }

}

package br.com.sga.persistencia <<Folder>> {

     abstract class Gerenciador {

     }

     class GerenciadorAlunos {

     }

     class GerenciadorEmpresa {

     }

     class GerenciadorHistoricoCaixa {

     }

     class GerenciadorUsuarios {

     }

}

package br.com.sga.pessoal <<Folder>> {

     abstract class Pessoa <<Comparable>> {

     }

     class Aluno extends Pessoa {

     }

     enum Sexo {

     }
}

Gerenciador <|-- GerenciadorAlunos
GerenciadorEmpresa
GerenciadorHistoricoCaixa
GerenciadorUsuarios

Pessoa *-- DateHelper
Pessoa *-- Endereco
Pessoa *-- Sexo

Aluno *-- Pagamento

GerenciadorUsuarios o-- Usuario


@enduml