/'
Diagrama UML do sistema de gerenciamento de academias (SGA)
Manual: https://plantuml.com/class-diagram#a05971470d7fd711
'/
@startuml sga
skinparam classAttributeIconSize 0

package br.com.sga.empresa <<Folder>> {
     class Empresa {
          -nome : String
          -cnpj : int
          -email : String
          -nomeDono : String
          -cpfDono : int
          -nomeResponsavel : String
          -cpfResponsavel : int
          -cidade : String
          -estado : Estado
          -valorMensalidade : double
          +Empresa(...)
          +toString() : String
     }

     enum Estado {
          AC
          AL
          AP
          AM
          BA
          CE
          DF
          ES
          GO
          MA
          MT
          MS
          MG
          PA
          PB
          PR
          PE
          PI
          RJ
          RN
          RS
          RO
          RR
          SC
          SP
          SE
          TO
          +toString() : String
     }
}

package br.com.sga.pessoal <<Folder>> {

     abstract class Pessoa <<Comparable>> {
          -nome : String
          -telefone : String
          -sexo : Sexo
          -dataNascimento : LocalDateTime
          -email : String
          -cpf : int
          -logradouro : String
          -bairro : String
          -cep : int
          +toString() : String
     }

     class Funcionario extends Pessoa {
          {static} -idIncremento : int
          -id : int
          -cargo : Cargo
          -salario : float
          -historicoPagamento : Map<LocalDateTime, Double>
          -dataAdmissao : LocalDateTime
          +Funcionario(...)
          +pagarSalario() : void
          +aumentoSalario() : void
          +hashCode() : int
          +equals(referential : Object) : boolean
          +toString() : String
     }

     class Aluno extends Pessoa {
          {static} -matriculaIncremento : int
          -matriculaNumero : int
          -historicoMensalidade : Map<LocalDateTime, Double>
          -dataMensalidade : LocalDateTime
          +Aluno(...)
          +pagarMensalidade(valorMensalidade : double) : void
          +verificarSituacao() : boolean
          +hashCode() : int
          +equals(referential : Object) : boolean
          +toString() : String
     }

     enum Cargo {
          ADMINISTRADOR
          GERENTE
          INSTRUTOR
          AVALIADOR_FISICO
          NUTRICIONISTA
          ATENDENTE
          LIMPEZA
          +toString() : String
     }

     enum Sexo {
          MASCULINO
          FEMININO
          OUTRO
          +toString() : String
     }
}

package br.com.sga.financeiro <<Folder>> {

     abstract class GerenciadorCaixa {
          -inicioCaixa : LocalDateTime
          -finalCaixa : LocalDateTime
          -dataAtual : LocalDateTime
          -totalData : Map<LocalDateTime, Double>
          +atualizarCaixa() : void
          {abstract} +abrirCaixa() : boolean
          {abstract} +fecharCaixa() : boolean
          +getInicioCaixa() : LocalDateTime
          +getFinalCaixa() : LocalDateTime
          +getAtualCaixa() : LocalDateTime
          +toString() : String
     }

     class GerenciadorAlunos extends GerenciadorCaixa {
          -mensalidades : Map<Aluno, Boolean>
          +GerenciadorAlunos()
          +verificarMensalidade(matricula : int) : boolean
          +adicionarAluno(aluno : Aluno) : void
          +adicionarAluno(alunos : Collection<Aluno>) : void
          +removerAluno() : Aluno
          +getAluno(matricula : int) : Aluno
          +getAlunos() : Set<Aluno>
          +toString() : String
     }

     class GerenciadorFuncionarios extends GerenciadorCaixa {
          -pagamentos : Map<Funcionario, Boolean>
          +GerenciadorFuncionarios()
          +verificarPagamento(id : int) : boolean
          +adicionarFuncionario(funcionario : Funcionario) : void
          +adicionarFuncionarios(funcionarios : Collection<Funcionario>) : void
          +removerFuncionario() : Funcionario
          +getFuncionario(id : int) : Funcionario
          +getFuncionarios() : Set<Funcionario>
          +toString() : String
     }
}

package br.com.sga.banco <<Folder>> {
     class GerenciadorBanco {
          -arquivoBanco : File
          +GerenciadorBanco(arquivoBanco : File)
          +salvarDados() : void
          +getBanco() : File
          +restaurarDados() : void
          +backupDados() : void
          +toString() : String
     }
}

Pessoa *-- Sexo

Funcionario *-- Cargo

GerenciadorFuncionarios *-- Funcionario

GerenciadorAlunos *-- Aluno

Empresa *-- Estado

@enduml