/'
Diagrama UML do Sistema de Gerenciamento de Academias (SGA)
Manual: https://plantuml.com/class-diagram#a05971470d7fd711
'/
@startuml sga
skinparam classAttributeIconSize 0

package br.com.sga.empresa <<Folder>> {
     class Empresa {
          -nome : String
          -cnpj : String
          -email : String
          -telefone : String
          -dono : Funcionario
          -responsavel : Funcionario
          -usuarioAdministrador : Usuario
          -localizacao : Endereco
          +Empresa(nomeEmpresa : String, cnpjEmpresa : String)
          +toString() : String
     }

     class Usuario {
          -login : String
          -senha : String
          +Usuario(login : String, senha : String)
          +getLogin() : String
          +getSenha() : String
          +toString() : String
     }
}

package br.com.sga.identidade <<Folder>> {

     class Endereco {
          -logradouro : String
          -bairro : String
          -cep : String
          -cidade : String
          -estado : Estado
     }

     enum Estado {
          AC
          AL
          AP
          AM
          BA
          CE
          DF
          ES
          GO
          MA
          MT
          MS
          MG
          PA
          PB
          PR
          PE
          PI
          RJ
          RN
          RS
          RO
          RR
          SC
          SP
          SE
          TO
          +toString() : String
     }

     class ValidacaoDadosPessoais {
          validarRegistroNacional(registro : String) : boolean
          validarEmail(email : String) : boolean
          validarTelefone(telefone : String) : boolean
     }

}
package br.com.sga.pessoal <<Folder>> {

     abstract class Pessoa <<Comparable>> {
          -nome : String
          -telefone : String
          -sexo : Sexo
          -dataNascimento : LocalDateTime
          -email : String
          -cpf : String
          -endereco : Endereco
          +toString() : String
     }

     class Funcionario extends Pessoa {

     }

     class Aluno extends Pessoa {
          {static} -matriculaIncremento : int
          -matriculaNumero : int
          -historicoMensalidade : Map<LocalDateTime, Double>
          -dataMensalidade : LocalDateTime
          +Aluno(...)
          +pagarMensalidade(valorMensalidade : double) : void
          +verificarSituacao() : boolean
          +hashCode() : int
          +equals(referential : Object) : boolean
          +toString() : String
     }

     enum Sexo {
          MASCULINO
          FEMININO
          OUTRO
          +toString() : String
     }
}

package br.com.sga.financeiro <<Folder>> {

     abstract class GerenciadorCaixa {
          -inicioCaixa : LocalDateTime
          -finalCaixa : LocalDateTime
          -dataAtual : LocalDateTime
          -totalData : Map<LocalDateTime, Double>
          +atualizarCaixa() : void
          {abstract} +abrirCaixa() : boolean
          {abstract} +fecharCaixa() : boolean
          +getInicioCaixa() : LocalDateTime
          +getFinalCaixa() : LocalDateTime
          +getAtualCaixa() : LocalDateTime
          +toString() : String
     }

     class GerenciadorAlunos extends GerenciadorCaixa {
          -mensalidades : Map<Aluno, Boolean>
          +GerenciadorAlunos()
          +verificarMensalidade(matricula : int) : boolean
          +adicionarAluno(aluno : Aluno) : void
          +adicionarAluno(alunos : Collection<Aluno>) : void
          +removerAluno() : Aluno
          +getAluno(matricula : int) : Aluno
          +getAlunos() : Set<Aluno>
          +toString() : String
     }
}

Pessoa *-- Sexo

GerenciadorAlunos *-- Aluno

Empresa *-- Estado

@enduml